SIG.UI/Areas/Maintenance/Controllers/BrandsController.cs
using AutoMapper;
using Azure.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using SIG.Core.Domain;
using SIG.Core.Domain.Interfaces;
using SIG.Services;
using SIG.UI.Base;

namespace SIG.UI.Areas.Maintenance
{
    [Area("Maintenance")]
    public class BrandsController : Controller
    {
        private readonly IBrandRepository _brand;
        private readonly IMapper _mapper;

        public BrandsController(IMapper mapper, IBrandRepository brand)
        {

            _mapper = mapper;
            _brand = brand;
        }

        /* public async Task<IActionResult> Index()
         {
             var br = await _brand.GetAll();
             var brm = _mapper.Map<IEnumerable<BrandViewModel>>(br);

             return View(brm);
         }*/
        [Route("/Maintenance/brands")]
        public async Task<IActionResult> Index(string searchString)
        {
            
            var str = searchString.IsNullOrEmpty() ? "" : searchString;
            var br = await _brand.GetByQueryReturnIEnumerable(x=>x.Name.Contains(str));
            var brm = _mapper.Map<IEnumerable<BrandViewModel>>(br);
        
                return View(brm);
        }
        public async Task<IActionResult> Details(Guid id)
        {

            return View(_mapper.Map<BrandViewModel>(await _brand.GetById(id)));
        }
        public async Task<IActionResult> Create()
        {
            
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(BrandViewModel model)
        {
            if (!ModelState.IsValid) return View();

            await _brand.Add(_mapper.Map<Brand>(model));
            return RedirectToAction(nameof(Index));
        }

       
        public async Task<IActionResult> Edit(Guid id)
        {

            return View(_mapper.Map<BrandViewModel>(await _brand.GetById(id)));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(BrandViewModel model)
        {
            if (!ModelState.IsValid) return View();

            await _brand.Update(_mapper.Map<Brand>(model));
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(Guid id)
        {

            return View(_mapper.Map<BrandViewModel>(await _brand.GetById(id)));
        }
        [HttpPost]
        public async Task<IActionResult> Delete(BrandViewModel model)
        {
            

            await _brand.Remove(model.Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

SIG.UI/Areas/Maintenance/Controllers/HistoricsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;
using SIG.Core.Domain;
using SIG.Core.Domain.Interfaces;
using SIG.Services;
using System.Numerics;

namespace SIG.UI.Areas.Maintenance
{
    [Area("Maintenance")]
    public class HistoricsController : Controller
    {
        private readonly IHistoricRepository _historic;
        private readonly IMapper _mapper;
        private readonly IComputerRepository _computer;
        public HistoricsController(IMapper mapper, IHistoricRepository historic, IComputerRepository computer)
        {

            _mapper = mapper;
            _historic = historic;
            _computer = computer;
        }

        /* public async Task<IActionResult> Index()
         {
             var br = await _historic.GetAll();
             var brm = _mapper.Map<IEnumerable<HistoricViewModel>>(br);

             return View(brm);
         }*/
        [Route("/Maintenance/historics")]
        public async Task<IActionResult> Index(string searchString)
        {
          

            var str = searchString.IsNullOrEmpty() ? "" : searchString;
            var br = await _historic.GetByQueryReturnIEnumerable(x=>x.Description.Contains(str));
            var brm = _mapper.Map<IEnumerable<HistoricViewModel>>(br);

            return View(brm);
        }
        public async Task<IActionResult> Details(Guid id)
        {

            return View(_mapper.Map<HistoricViewModel>(await _historic.GetById(id)));
        }
        public async Task<IActionResult> Create()
        {
            var computer = await _computer.GetAll();
            ViewBag.ComputerId = new SelectList(_mapper.Map<IEnumerable<ComputerViewModel>>(computer), "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(HistoricViewModel model)
        {
            if (!ModelState.IsValid) return View();

            await _historic.Add(_mapper.Map<Historic>(model));
            return RedirectToAction(nameof(Index));
        }

       
        public async Task<IActionResult> Edit(Guid id)
        {
            var computer = await _computer.GetAll();
            ViewBag.ComputerId = new SelectList(_mapper.Map<IEnumerable<ComputerViewModel>>(computer), "Id", "Name");

            return View(_mapper.Map<HistoricViewModel>(await _historic.GetById(id)));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(HistoricViewModel model)
        {
            if (!ModelState.IsValid) return View();

            await _historic.Update(_mapper.Map<Historic>(model));
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(Guid id)
        {

            return View(_mapper.Map<HistoricViewModel>(await _historic.GetById(id)));
        }
        [HttpPost]
        public async Task<IActionResult> Delete(HistoricViewModel model)
        {
            

            await _historic.Remove(model.Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

SIG.UI/Areas/Maintenance/Controllers/SectorsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using SIG.Core.Domain;
using SIG.Core.Domain.Interfaces;
using SIG.Services;

namespace SIG.UI.Areas.Maintenance
{
    [Area("Maintenance")]
    public class SectorsController : Controller
    {
        private readonly ISectorRepository _sector;
        private readonly IMapper _mapper;

        public SectorsController(IMapper mapper, ISectorRepository sector)
        {

            _mapper = mapper;
            _sector = sector;
        }

        /* public async Task<IActionResult> Index()
         {
             var br = await _sector.GetAll();
             var brm = _mapper.Map<IEnumerable<SectorViewModel>>(br);

             return View(brm);
         }*/
        [Route("/Maintenance/sectors")]
        public async Task<IActionResult> Index(string searchString)
        {
            var str = searchString.IsNullOrEmpty() ? "" : searchString;
            var br = await _sector.GetByQueryReturnIEnumerable(x=>x.Name.Contains(str));
            var brm = _mapper.Map<IEnumerable<SectorViewModel>>(br);

            return View(brm);
        }
        public async Task<IActionResult> Details(Guid id)
        {

            return View(_mapper.Map<SectorViewModel>(await _sector.GetById(id)));
        }
        public async Task<IActionResult> Create()
        {
            
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(SectorViewModel model)
        {
            if (!ModelState.IsValid) return View();

            await _sector.Add(_mapper.Map<Sector>(model));
            return RedirectToAction(nameof(Index));
        }

       
        public async Task<IActionResult> Edit(Guid id)
        {

            return View(_mapper.Map<SectorViewModel>(await _sector.GetById(id)));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(SectorViewModel model)
        {
            if (!ModelState.IsValid) return View();

            await _sector.Update(_mapper.Map<Sector>(model));
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(Guid id)
        {

            return View(_mapper.Map<SectorViewModel>(await _sector.GetById(id)));
        }
        [HttpPost]
        public async Task<IActionResult> Delete(SectorViewModel model)
        {
            

            await _sector.Remove(model.Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

SIG.UI/Controllers/ComputersController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SIG.Core.Domain;
using SIG.Core.Domain.Interfaces;
using SIG.Data;
using SIG.Services;
using SIG.UI.Base;

namespace SIG.UI.Controllers
{
  //  [Route("Home/"+Program.guid)]
    public class ComputersController : Controller
    {
        private readonly IComputerRepository _computerRepository;
        private readonly IMapper _mapper;
        public ComputersController(IComputerRepository computerRepository, IMapper mapper)
        {
            _computerRepository = computerRepository;
            _mapper = mapper;
        }

        // GET: Computers
        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<ComputerViewModel>>(await _computerRepository.GetAll()));
                         
        }

        // GET: Computers/Details/5
        [Route(GuidRoutes.Details)]

        public async Task<IActionResult> Details(Guid id)
        {
            var computerViewModel = await GetComputer(id);
            if (computerViewModel == null) return NotFound();
            
            return View(computerViewModel);
        }

        // GET: Computers/Create
        [Route(GuidRoutes.Create)]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Computers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ComputerViewModel computerViewModel)
        {
            if (!ModelState.IsValid) return View(computerViewModel);
            
                var computer=_mapper.Map<Computer>(computerViewModel);
            await _computerRepository.Add(computer);
            return RedirectToAction("Index");
        }

        // GET: Computers/Edit/5
        [Route(GuidRoutes.Edit)]
        public async Task<IActionResult> Edit(Guid id)
        {
            var computerViewModel = await GetComputer(id);
            if (computerViewModel == null) return NotFound();

            return View(computerViewModel);

          
        }

        // POST: Computers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, ComputerViewModel computerViewModel)
        {
            if (id != computerViewModel.Id) return NotFound();


            if (!ModelState.IsValid) return View(computerViewModel);

            var computer = _mapper.Map<Computer>(computerViewModel);
            await _computerRepository.Update(computer);
            return RedirectToAction("Index");
        }

        // GET: Computers/Delete/5
        [Route(GuidRoutes.Delete)]

        public async Task<IActionResult> Delete(Guid id)
        {
            var computerViewModel = await GetComputer(id);
            if (computerViewModel == null) return NotFound();

            return View(computerViewModel);

        }

        // POST: Computers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var computerViewModel = await GetComputer(id);
            if (computerViewModel == null) return NotFound();

            await _computerRepository.Remove(id);
            return RedirectToAction("index");
        }

   
        private async Task<ComputerViewModel> GetComputer(Guid id)
        {
            return _mapper.Map<ComputerViewModel>(await _computerRepository.GetById(id));
        }
    }
}

SIG.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SIG.UI</title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SIG.UI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link href="~/lib/datatables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
</head>
<body style="background-color:whitesmoke">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  
          navbar-dark bg-dark border-bottom box-shadow ">
            <div class="container-fluid" >
                <a  class="navbar-brand text-white-50" asp-area="" asp-controller="Home" asp-action="Index">SIG.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul  class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa-solid fa-book-medical"></i><span style="color:transparent">*</span>  Cadastros
                                </a>
                                <div class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdownMenuLink">

                                    <a class="dropdown-item" asp-area="Maintenance" asp-controller="Brands" asp-action="Index">
                                        <i class="fa-solid fa-industry"></i><span style="color:transparent">**</span>  Fabricantes
                                    </a>
                                    <a class="dropdown-item" asp-area="Maintenance" asp-controller="EquipTypes" asp-action="Index">
                                        <i class="fa-solid fa-server"></i><span style="color:transparent">**</span>   Tipos de Equipamento
                                    </a>
                                    <a class="dropdown-item" asp-area="Maintenance" asp-controller="ActingAreas" asp-action="Index">
                                        <i class="fa-solid fa-globe"></i><span style="color:transparent">**</span>   Áreas
                                    </a>
                                    <a class="dropdown-item" asp-area="Maintenance" asp-controller="Locacities" asp-action="Index">
                                        <i class="fa-solid fa-building"></i><span style="color:transparent">**</span>   Unidades
                                    </a>
                                    <a class="dropdown-item" asp-area="Maintenance" asp-controller="Sectors" asp-action="Index">
                                        <i class="fa-solid fa-vector-square"></i><span style="color:transparent">**</span>   Setores
                                    </a>
                                </div>
                            </li>



                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa-solid fa-computer"></i><span style="color:transparent">*</span>   Computadores
                                </a>
                                <div class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-area="Maintenance" asp-controller="Computers" asp-action="Index">
                                        <i class="fa-solid fa-server"></i><span style="color:transparent">*</span> Cadastro
                                    </a>
                                    <a class="dropdown-item" asp-area="Maintenance" asp-controller="Historics" asp-action="Index">
                                        <i class="fa-solid fa-clock-rotate-left"></i><span style="color:transparent">*</span> Ocorrências
                                    </a>
                                </div>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
  
   

     


  
    <div class="container-fluid" >
  
        <main role="main" class="p-3">
            @RenderBody()
        </main>
    </div>
    
    <div class="modal fade" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" id="form-modal">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    @*<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>*@
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SIG.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>