SIG.UI/Areas/Maintenance/Controllers/ActingAreasController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using SIG.Core.Domain;
using SIG.Core.Domain.Interfaces;
using SIG.Services;

namespace SIG.UI.Areas.Maintenance
{
    [Area("Maintenance")]
    public class ActingAreasController : Controller
    {
        private readonly IActingAreaRepository _actingArea;
        private readonly IMapper _mapper;

        public ActingAreasController(IMapper mapper, IActingAreaRepository actingArea)
        {

            _mapper = mapper;
            _actingArea = actingArea;
        }

        /* public async Task<IActionResult> Index()
         {
             var br = await _actingArea.GetAll();
             var brm = _mapper.Map<IEnumerable<ActingAreaViewModel>>(br);

             return View(brm);
         }*/
        [Route("/Maintenance/actingAreas")]
        public async Task<IActionResult> Index(string searchString)
        {
            var str = searchString.IsNullOrEmpty() ? "" : searchString;
            var br = await _actingArea.GetByQueryReturnIEnumerable(x=>x.Name.Contains(str));
            var brm = _mapper.Map<IEnumerable<ActingAreaViewModel>>(br);

            return View(brm);
        }
        public async Task<IActionResult> Details(Guid id)
        {

            return View(_mapper.Map<ActingAreaViewModel>(await _actingArea.GetById(id)));
        }
        [HttpGet]
        [Route("/Maintenance/actingAreas/create")]
        public async Task<IActionResult> Create()
        {
            
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ActingAreaViewModel model)
        {
            if (!ModelState.IsValid) return View();

            await _actingArea.Add(_mapper.Map<ActingArea>(model));
            return RedirectToAction(nameof(Index));
        }

       
        public async Task<IActionResult> Edit(Guid id)
        {

            return View(_mapper.Map<ActingAreaViewModel>(await _actingArea.GetById(id)));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ActingAreaViewModel model)
        {
            if (!ModelState.IsValid) return View();

            await _actingArea.Update(_mapper.Map<ActingArea>(model));
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(Guid id)
        {

            return View(_mapper.Map<ActingAreaViewModel>(await _actingArea.GetById(id)));
        }
        [HttpPost]
        public async Task<IActionResult> Delete(ActingAreaViewModel model)
        {
            

            await _actingArea.Remove(model.Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

SIG.UI/Areas/Maintenance/Views/ActingAreas/Create.cshtml
@model SIG.Services.ActingAreaViewModel

@{
    ViewData["Title"] = "Create";
  
}

<h2>Adicionar novo área</h2>
<hr />

<div class="row">
    <div class="col">

        <form asp-area="Maintenance" asp-controller="ActingAreas" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
  
           
            
           
            <br />
            <hr />

            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SIG.UI/Areas/Maintenance/Views/ActingAreas/Delete.cshtml
@model SIG.Services.ActingAreaViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = null;
}




<div class="row">
    <div class="col-md-4">

        <form asp-area="Maintenance" asp-controller="ActingAreas" asp-action="Delete">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
           <br />
            <div class="form-group d-flex">
                <input type="submit" value="Excluir" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary" style="margin-left:5px;">Cancelar</a>
            </div>
           
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SIG.UI/Areas/Maintenance/Views/ActingAreas/Edit.cshtml
@model SIG.Services.ActingAreaViewModel

@{
    ViewData["Title"] = "Edit";
   
}
<h2>Editar área (@Model.Name)</h2>
<hr />
<div class="row">
    <div class="col">

        <form asp-area="Maintenance" asp-controller="ActingAreas" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
  
           
            
           
             <br />
             <hr />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SIG.UI/Areas/Maintenance/Views/ActingAreas/Index.cshtml
@model IEnumerable<SIG.Services.ActingAreaViewModel>

@{
    ViewData["Title"] = "Index";


}

<h2>Cadastro de Áreas</h2>
<hr />
<table class="table">
    <tr>
        <th> <a asp-area="Maintenance" asp-controller="ActingAreas" asp-action="Create" class="btn btn-success"><i class="fa-solid fa-plus"></i>Adicionar</a></th>

        <th class="justify-content-end d-flex">
            <form class="d-flex" asp-controller="ActingAreas" asp-action="Index">

                <input type="text" name="SearchString" class="form-control" style="max-width:400px;" />

                <button type="submit" value="" class="form-control" style="background-color: #0082ca;width:50px;margin-left:5px"><i class="fa-solid fa-search"></i></button></>

            </form>
        </th>
    </tr>


</table>
<table class="table table-striped table-bordered" style="border-color:#c1c1c1;">
    <thead class="table-dark">
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th style="width: 180px;text-align:right">
                @Html.DisplayNameFor(model => model.ModifyDate)
            </th>
            <th style="width: 150px;text-align:center">Ações</th>


        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr style="vertical-align:middle">
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td align="right">
                    @Html.DisplayFor(modelItem => item.ModifyDate)
                </td>

                <td align="right">
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning"><i class="fa-solid fa-pen-to-square"></i></a>
                    <a onclick="showInPopup('/maintenance/actingAreas/delete/@item.Id','Deseja excluir Área (@item.Name)?')" class="btn btn-danger"><i class="fa-solid fa-trash-can text-dark"></i></a>




                </td>
            </tr>
        }
    </tbody>
</table>